version: '3'

services:
  server:
    image: node:latest
    ports:
      - '5001:5001'
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile

  postgres:
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    build:
      dockerfile: ./server/db/Dockerfile
    volumes:
      - postgres-db:/data/db

volumes:
  postgres-db:
